# Generated by Django 5.0.6 on 2024-06-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
