# Generated by Django 5.0.6 on 2024-06-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Gender',
            new_name='gender',
        ),
    ]
