# Generated by Django 5.0.6 on 2024-06-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='no_days',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
