# Generated by Django 5.0.6 on 2024-07-03 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_remove_cart_cart_id_remove_cart_item_user_cart_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_item',
            name='cart_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Authentication.cart'),
        ),
    ]
