# Generated by Django 5.0.6 on 2024-07-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0007_remove_cart_item_cart_total_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='incart',
            field=models.BooleanField(default=False),
        ),
    ]
